name: Facebook Scrapping Workflow

on:
  push:
    branches:
      - dev--arthur

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run the application
        env:
          FACEBOOK_EMAIL: ${{ secrets.FACEBOOK_EMAIL }}
          FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
        run: |
          npm start
