name: Facebook Scrapping Workflow

on:
  push:
    branches:
      - dev--arthur

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          NODE_VERSION="16.x"
          curl -fsSL https://deb.nodesource.com/setup_$NODE_VERSION | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install dependencies
        run: npm install

      - name: Run the application
        env:
          FACEBOOK_EMAIL: ${{ secrets.FACEBOOK_EMAIL }}
          FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
        run: |
          npm start
